### ISSUE TITLE
403 forbidden with scanny.

### ISSUE THREAD

**Issue by Soullivaneuh** [wpscanteam/vulndb#33]
I have a background job task system which run wpscan several time per day.

This is failing on getting vulnerabilities file.

If I try it manually with a wget from server:

```
$ wget https://wpvulndb.com/data/local_vulnerable_files.xml.sha512
--2015-06-16 11:39:01--  https://wpvulndb.com/data/local_vulnerable_files.xml.sha512
Resolving wpvulndb.com... 85.159.212.89, 2a01:7e00::f03c:91ff:fe73:9730
Connecting to wpvulndb.com|85.159.212.89|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-06-16 11:39:01 ERROR 403: Forbidden.
```

What is the reason?

Thanks.

**Comment by ethicalhack3r** [comment]
Hi @Soullivaneuh,

We saw that an unknown server was requesting our database files on multiple occasions. We blocked the server's IP to prevent abuse.

Is this server one of yours? Can you give us some information as to what it is doing and what it is for?

Thanks,
Ryan

**Comment by gallart** [comment]
Yes, this server is one of ours.

We are using it for scanning our Wordpress installations.

**Comment by Soullivaneuh** [comment]
If you are not comfortable with automatic wget on your server, maybe you can change your lib to get it directly from Github or allow people to custom the url by parameter.

**Comment by ethicalhack3r** [comment]
Can you provide/confirm the IP addresses that you are using so that we can unblock them and ensure they are not blocked in the future? can email them to wpscanteam at gmail.com

**Comment by ethicalhack3r** [comment]
@Soullivaneuh the Github repository will be deprecated in the near future. All updates will and should be from wpvulndb.com

**Comment by Soullivaneuh** [comment]
Email sent. Thanks.
